// Server-rendered banner shown at the top and bottom of any Property Spotlight
// page flagged as a sample. Makes it impossible for a prospective Featured
// Realtor partner (or any visitor) to mistake the article for a real listing.

import Link from 'next/link';
import { Info, ArrowUpRight } from 'lucide-react';

export default function SampleBanner({ variant = 'top' }) {
  if (variant === 'bottom') {
    return (
      <aside className="mt-16 bg-palm text-sand-50 p-6 md:p-8 rounded-lg">
        <div className="text-[11px] uppercase tracking-[0.28em] text-gold mb-3">
          This is a sample Property Spotlight
        </div>
        <h3 className="font-serif text-2xl md:text-3xl leading-tight mb-3">
          Real Property Spotlights for our Featured Realtor partner appear in the main blog feed with full distribution.
        </h3>
        <p className="text-sand-50/80 text-sm md:text-base leading-relaxed max-w-2xl">
          The byline links to your collaborator profile, the article is indexed by Google with Person-attributed Article schema for authorship credit, and every lead generated by the article routes directly to you.
        </p>
        <Link
          href="/collaborate"
          className="mt-6 inline-flex items-center gap-2 bg-gold text-palm font-semibold tracking-[0.18em] uppercase text-xs px-7 py-3.5 hover:bg-gold/90 transition-colors"
        >
          Apply for the Featured Realtor Slot <ArrowUpRight size={14} />
        </Link>
      </aside>
    );
  }

  // Top variant — slim, attention-grabbing, immediately above the article hero.
  return (
    <div className="bg-gold/15 border-y border-gold/30">
      <div className="container py-3 flex flex-col md:flex-row md:items-center md:justify-between gap-2 text-sm">
        <div className="flex items-start md:items-center gap-2.5 text-palm">
          <Info size={16} className="shrink-0 mt-0.5 md:mt-0 text-gold-dark" />
          <span>
            <strong className="font-semibold">Sample Property Spotlight.</strong>{' '}
            <span className="text-palm/85">
              This is an example of the editorial coverage your listings receive as our Featured Realtor partner.
            </span>
          </span>
        </div>
        <Link
          href="/collaborate"
          className="text-[11px] uppercase tracking-[0.22em] text-terracotta hover:text-palm whitespace-nowrap inline-flex items-center gap-1"
        >
          Apply to be the Featured Realtor <ArrowUpRight size={12} />
        </Link>
      </div>
    </div>
  );
}
